// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tally.Data;

#nullable disable

namespace Tally.Data.Migrations
{
    [DbContext(typeof(TallyDbContext))]
    [Migration("20260211003613_AddFoodDatabaseEntities")]
    partial class AddFoodDatabaseEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LocationUser", b =>
                {
                    b.Property<int>("LocationsId")
                        .HasColumnType("integer");

                    b.Property<string>("UsersId")
                        .HasColumnType("text");

                    b.HasKey("LocationsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserLocations", (string)null);
                });

            modelBuilder.Entity("Tally.Data.Entities.CommonCatagory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<TimeSpan>("ExpirationTimeWhenClosed")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("ExpirationTimeWhenOpen")
                        .HasColumnType("interval");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("CommonCatagories");

                    b.HasDiscriminator().HasValue("CommonCatagory");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Tally.Data.Entities.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("Tally.Data.Entities.FoodDatabaseFastSearch", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Brands")
                        .HasColumnType("text");

                    b.Property<string>("GenericName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<string>("SearchContent")
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("FoodDatabaseFastSearch");
                });

            modelBuilder.Entity("Tally.Data.Entities.FoodDatabaseSlowSearch", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("AbbreviatedProductName")
                        .HasColumnType("text");

                    b.Property<decimal?>("Acidity100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AddedSalt100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AddedSugars100g")
                        .HasColumnType("numeric");

                    b.Property<string>("Additives")
                        .HasColumnType("text");

                    b.Property<string>("AdditivesEn")
                        .HasColumnType("text");

                    b.Property<int?>("AdditivesN")
                        .HasColumnType("integer");

                    b.Property<string>("AdditivesTags")
                        .HasColumnType("text");

                    b.Property<decimal?>("Alcohol100g")
                        .HasColumnType("numeric");

                    b.Property<string>("Allergens")
                        .HasColumnType("text");

                    b.Property<string>("AllergensEn")
                        .HasColumnType("text");

                    b.Property<decimal?>("AlphaLinolenicAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ArachidicAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ArachidonicAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BehenicAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BetaCarotene100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BetaGlucan100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Bicarbonate100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Biotin100g")
                        .HasColumnType("numeric");

                    b.Property<string>("BrandOwner")
                        .HasColumnType("text");

                    b.Property<string>("Brands")
                        .HasColumnType("text");

                    b.Property<string>("BrandsEn")
                        .HasColumnType("text");

                    b.Property<string>("BrandsTags")
                        .HasColumnType("text");

                    b.Property<decimal?>("ButyricAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Caffeine100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Calcium100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CapricAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CaproicAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CaprylicAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Carbohydrates100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CarbohydratesTotal100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CarbonFootprint100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CarbonFootprintFromMeatOrFish100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Carnitine100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Casein100g")
                        .HasColumnType("numeric");

                    b.Property<string>("Categories")
                        .HasColumnType("text");

                    b.Property<string>("CategoriesEn")
                        .HasColumnType("text");

                    b.Property<string>("CategoriesTags")
                        .HasColumnType("text");

                    b.Property<decimal?>("CeroticAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Chloride100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Chlorophyl100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Cholesterol100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Choline100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Chromium100g")
                        .HasColumnType("numeric");

                    b.Property<string>("Cities")
                        .HasColumnType("text");

                    b.Property<string>("CitiesTags")
                        .HasColumnType("text");

                    b.Property<decimal?>("Cocoa100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CollagenMeatProteinRatio100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Completeness")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Copper100g")
                        .HasColumnType("numeric");

                    b.Property<string>("Countries")
                        .HasColumnType("text");

                    b.Property<string>("CountriesEn")
                        .HasColumnType("text");

                    b.Property<string>("CountriesTags")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedT")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .HasColumnType("text");

                    b.Property<string>("DataQualityErrorsTags")
                        .HasColumnType("text");

                    b.Property<decimal?>("DihomoGammaLinolenicAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DocosahexaenoicAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EicosapentaenoicAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ElaidicAcid100g")
                        .HasColumnType("numeric");

                    b.Property<string>("EmbCodes")
                        .HasColumnType("text");

                    b.Property<string>("EmbCodesTags")
                        .HasColumnType("text");

                    b.Property<decimal?>("Energy100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EnergyFromFat100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EnergyKcal100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EnergyKj100g")
                        .HasColumnType("numeric");

                    b.Property<string>("EnvironmentalScoreGrade")
                        .HasColumnType("text");

                    b.Property<decimal?>("EnvironmentalScoreScore")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ErucicAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Erythritol100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Fat100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Fiber100g")
                        .HasColumnType("numeric");

                    b.Property<string>("FirstPackagingCodeGeo")
                        .HasColumnType("text");

                    b.Property<decimal?>("Fluoride100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Folates100g")
                        .HasColumnType("numeric");

                    b.Property<string>("FoodGroups")
                        .HasColumnType("text");

                    b.Property<string>("FoodGroupsEn")
                        .HasColumnType("text");

                    b.Property<string>("FoodGroupsTags")
                        .HasColumnType("text");

                    b.Property<decimal?>("Fructose100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FruitsVegetablesNuts100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FruitsVegetablesNutsDried100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FruitsVegetablesNutsEstimate100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FruitsVegetablesNutsEstimateFromIngredients100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Galactose100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("GammaLinolenicAcid100g")
                        .HasColumnType("numeric");

                    b.Property<string>("GenericName")
                        .HasColumnType("text");

                    b.Property<decimal?>("Glucose100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("GlycemicIndex100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("GondoicAcid100g")
                        .HasColumnType("numeric");

                    b.Property<string>("ImageIngredientsSmallUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageIngredientsUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageNutritionSmallUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageNutritionUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageSmallUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("IngredientsAnalysisTags")
                        .HasColumnType("text");

                    b.Property<string>("IngredientsTags")
                        .HasColumnType("text");

                    b.Property<string>("IngredientsText")
                        .HasColumnType("text");

                    b.Property<decimal?>("Inositol100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InsolubleFiber100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Iodine100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Iron100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Isomalt100g")
                        .HasColumnType("numeric");

                    b.Property<string>("Labels")
                        .HasColumnType("text");

                    b.Property<string>("LabelsEn")
                        .HasColumnType("text");

                    b.Property<string>("LabelsTags")
                        .HasColumnType("text");

                    b.Property<decimal?>("Lactose100g")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("LastImageDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastImageT")
                        .HasColumnType("bigint");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastModifiedT")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastUpdatedDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastUpdatedT")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("LauricAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LignocericAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LinoleicAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Magnesium100g")
                        .HasColumnType("numeric");

                    b.Property<string>("MainCategory")
                        .HasColumnType("text");

                    b.Property<string>("MainCategoryEn")
                        .HasColumnType("text");

                    b.Property<decimal?>("Maltitol100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Maltodextrins100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Maltose100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Manganese100g")
                        .HasColumnType("numeric");

                    b.Property<string>("ManufacturingPlaces")
                        .HasColumnType("text");

                    b.Property<string>("ManufacturingPlacesTags")
                        .HasColumnType("text");

                    b.Property<decimal?>("MeadAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MelissicAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Methylsulfonylmethane100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Molybdenum100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MonounsaturatedFat100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MontanicAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MyristicAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NervonicAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Nitrate100g")
                        .HasColumnType("numeric");

                    b.Property<string>("NoNutritionData")
                        .HasColumnType("text");

                    b.Property<int?>("NovaGroup")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Nucleotides100g")
                        .HasColumnType("numeric");

                    b.Property<string>("NutrientLevelsTags")
                        .HasColumnType("text");

                    b.Property<string>("NutriscoreGrade")
                        .HasColumnType("text");

                    b.Property<decimal?>("NutriscoreScore")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NutritionScoreFr100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NutritionScoreUk100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OleicAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Omega3Fat100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Omega6Fat100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Omega9Fat100g")
                        .HasColumnType("numeric");

                    b.Property<string>("Origins")
                        .HasColumnType("text");

                    b.Property<string>("OriginsEn")
                        .HasColumnType("text");

                    b.Property<string>("OriginsTags")
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<string>("Packaging")
                        .HasColumnType("text");

                    b.Property<string>("PackagingEn")
                        .HasColumnType("text");

                    b.Property<string>("PackagingTags")
                        .HasColumnType("text");

                    b.Property<string>("PackagingText")
                        .HasColumnType("text");

                    b.Property<decimal?>("PalmiticAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PantothenicAcid100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Ph100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Phosphorus100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Phylloquinone100g")
                        .HasColumnType("numeric");

                    b.Property<string>("PnnsGroups1")
                        .HasColumnType("text");

                    b.Property<string>("PnnsGroups2")
                        .HasColumnType("text");

                    b.Property<decimal?>("Polydextrose100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Polyols100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PolyunsaturatedFat100g")
                        .HasColumnType("numeric");

                    b.Property<string>("PopularityTags")
                        .HasColumnType("text");

                    b.Property<decimal?>("Potassium100g")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<string>("ProductQuantity")
                        .HasColumnType("text");

                    b.Property<decimal?>("Proteins100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Psicose100g")
                        .HasColumnType("numeric");

                    b.Property<string>("PurchasePlaces")
                        .HasColumnType("text");

                    b.Property<string>("Quantity")
                        .HasColumnType("text");

                    b.Property<decimal?>("Salt100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SaturatedFat100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Selenium100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SerumProteins100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ServingQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("ServingSize")
                        .HasColumnType("text");

                    b.Property<decimal?>("Silica100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Sodium100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SolubleFiber100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Sorbitol100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Starch100g")
                        .HasColumnType("numeric");

                    b.Property<string>("States")
                        .HasColumnType("text");

                    b.Property<string>("StatesEn")
                        .HasColumnType("text");

                    b.Property<string>("StatesTags")
                        .HasColumnType("text");

                    b.Property<decimal?>("StearicAcid100g")
                        .HasColumnType("numeric");

                    b.Property<string>("Stores")
                        .HasColumnType("text");

                    b.Property<decimal?>("Sucrose100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Sugars100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Sulphate100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Taurine100g")
                        .HasColumnType("numeric");

                    b.Property<string>("Traces")
                        .HasColumnType("text");

                    b.Property<string>("TracesEn")
                        .HasColumnType("text");

                    b.Property<string>("TracesTags")
                        .HasColumnType("text");

                    b.Property<decimal?>("TransFat100g")
                        .HasColumnType("numeric");

                    b.Property<long?>("UniqueScansN")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("UnsaturatedFat100g")
                        .HasColumnType("numeric");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<decimal?>("VitaminA100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VitaminB1100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VitaminB12100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VitaminB2100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VitaminB6100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VitaminB9100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VitaminC100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VitaminD100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VitaminE100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VitaminK100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VitaminPp100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WaterHardness100g")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Zinc100g")
                        .HasColumnType("numeric");

                    b.HasKey("Code");

                    b.ToTable("FoodDatabaseSlowSearch");
                });

            modelBuilder.Entity("Tally.Data.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<int?>("CommonCatagoryId")
                        .HasColumnType("integer");

                    b.Property<int>("ContainerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CustomCatagoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FoodDatabaseCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OpenedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("CommonCatagoryId");

                    b.HasIndex("ContainerId");

                    b.HasIndex("CustomCatagoryId");

                    b.HasIndex("FoodDatabaseCode");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Tally.Data.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Tally.Data.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Tally.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tally.Data.Entities.CustomCatagory", b =>
                {
                    b.HasBaseType("Tally.Data.Entities.CommonCatagory");

                    b.HasDiscriminator().HasValue("CustomCatagory");
                });

            modelBuilder.Entity("LocationUser", b =>
                {
                    b.HasOne("Tally.Data.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tally.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tally.Data.Entities.Container", b =>
                {
                    b.HasOne("Tally.Data.Entities.Room", "Room")
                        .WithMany("Containers")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Tally.Data.Entities.FoodDatabaseSlowSearch", b =>
                {
                    b.HasOne("Tally.Data.Entities.FoodDatabaseFastSearch", "FastSearchData")
                        .WithOne("SlowSearchData")
                        .HasForeignKey("Tally.Data.Entities.FoodDatabaseSlowSearch", "Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FastSearchData");
                });

            modelBuilder.Entity("Tally.Data.Entities.Item", b =>
                {
                    b.HasOne("Tally.Data.Entities.CommonCatagory", "CommonCatagory")
                        .WithMany("CommonCatagoryItems")
                        .HasForeignKey("CommonCatagoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tally.Data.Entities.Container", "Container")
                        .WithMany("Items")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tally.Data.Entities.CustomCatagory", "CustomCatagory")
                        .WithMany("CustomCatagoryItems")
                        .HasForeignKey("CustomCatagoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tally.Data.Entities.FoodDatabaseSlowSearch", "FoodDatabaseEntry")
                        .WithMany()
                        .HasForeignKey("FoodDatabaseCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CommonCatagory");

                    b.Navigation("Container");

                    b.Navigation("CustomCatagory");

                    b.Navigation("FoodDatabaseEntry");
                });

            modelBuilder.Entity("Tally.Data.Entities.Room", b =>
                {
                    b.HasOne("Tally.Data.Entities.Location", "Location")
                        .WithMany("Rooms")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Tally.Data.Entities.CommonCatagory", b =>
                {
                    b.Navigation("CommonCatagoryItems");
                });

            modelBuilder.Entity("Tally.Data.Entities.Container", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Tally.Data.Entities.FoodDatabaseFastSearch", b =>
                {
                    b.Navigation("SlowSearchData");
                });

            modelBuilder.Entity("Tally.Data.Entities.Location", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Tally.Data.Entities.Room", b =>
                {
                    b.Navigation("Containers");
                });

            modelBuilder.Entity("Tally.Data.Entities.CustomCatagory", b =>
                {
                    b.Navigation("CustomCatagoryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
